### ISSUE TITLE
QR Generation Logic

### ISSUE THREAD

**Issue by A2va** [A2va/dai-qr-code#1]
Implement the QR generation.
Either by taking an existing library or if that library doesn't provided an interface to work with the Java I/O API that we talk about in the course, modify it's code.

Relevant ressources:

https://en.wikipedia.org/wiki/QR_code#Design
https://github.com/Auties00/QrToTerminal
https://github.com/nayuki/QR-Code-generator

**Comment by Forestierr** [comment]
I see here [Java - Generate QR Code using zxing](https://34codefactory.medium.com/java-generate-qr-code-using-zxing-code-factory-e4c3e6df2d77) that we can return a byte array of the QR code using ByteArrayOutputStream.
